package dockerapi

// Finding and removing containers, which is what an orphan sweep is made of.

import (
	"context"
	"os/exec"
	"strings"
	"testing"
	"time"
)

// startLabelled runs a throwaway container wearing labels, returning its name.
// Started through the CLI deliberately: this file tests the code that FINDS
// and REMOVES containers, and a fixture built by that same code could hide a
// matched pair of mistakes.
func startLabelled(t *testing.T, labels map[string]string) string {
	t.Helper()

	name := "steps-test-" + strings.ReplaceAll(t.Name(), "/", "-")

	args := make([]string, 0, 5+2*len(labels)+5)
	args = append(args, "run", "-d", "--rm", "--name", name)

	for key, value := range labels {
		args = append(args, "--label", key+"="+value)
	}

	args = append(args, "--", testImage, "sh", "-c", "sleep 120")

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	out, err := exec.CommandContext(ctx, "docker", args...).CombinedOutput() //nolint:gosec // every value is generated by this test
	if err != nil {
		t.Skipf("cannot start a fixture container: %v\n%s", err, out)
	}

	t.Cleanup(func() { removeFixture(name) })

	return name
}

func TestListContainersMatchesEveryLabel(t *testing.T) {
	client := requireDaemon(t)

	name := startLabelled(t, map[string]string{"steps.test.owner": "sweep", "steps.test.run": t.Name()})

	found, err := client.ListContainers(context.Background(), map[string]string{
		"steps.test.owner": "sweep",
		"steps.test.run":   t.Name(),
	})
	if err != nil {
		t.Fatalf("ListContainers: %v", err)
	}

	if len(found) != 1 {
		t.Fatalf("found %d containers, want exactly the one this test started", len(found))
	}

	// The labels come back structured. That is the point of asking this way:
	// the old shape formatted them into a line and parsed them out again, and
	// a label whose value contained a space could not survive the round trip.
	if found[0].Labels["steps.test.run"] != t.Name() {
		t.Errorf("labels = %v, want the values the container was started with", found[0].Labels)
	}

	if found[0].ID == "" {
		t.Error("the container has no id; nothing can be removed by it")
	}

	_ = name
}

// TestListContainersRequiresAllLabels pins that the filter is an AND.
//
// An OR would sweep containers belonging to another machine or another live
// process, which is the one mistake in this area that destroys a working
// build rather than merely failing to tidy one up.
func TestListContainersRequiresAllLabels(t *testing.T) {
	client := requireDaemon(t)

	startLabelled(t, map[string]string{"steps.test.owner": "sweep"})

	found, err := client.ListContainers(context.Background(), map[string]string{
		"steps.test.owner": "sweep",
		"steps.test.host":  "some-other-machine",
	})
	if err != nil {
		t.Fatalf("ListContainers: %v", err)
	}

	if len(found) != 0 {
		t.Errorf("found %d containers, want none: a container matching only one label is not ours", len(found))
	}
}

// TestListContainersIncludesStoppedOnes pins that the sweep can see the
// containers most worth reclaiming.
//
// A steps process killed outright leaves a container whose keepalive later
// expires, and it then sits as an Exited row. Listing only RUNNING containers
// would leave exactly those behind forever.
func TestListContainersIncludesStoppedOnes(t *testing.T) {
	client := requireDaemon(t)

	name := "steps-test-exited-fixture"

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	out, err := exec.CommandContext(ctx, "docker", "run", "-d", "--name", name,
		"--label", "steps.test.owner=exited", "--", testImage, "true").CombinedOutput()
	if err != nil {
		t.Skipf("cannot start a fixture container: %v\n%s", err, out)
	}

	t.Cleanup(func() { removeFixture(name) })

	// It runs `true`, so it is already on its way out; give it a moment to be
	// recorded as exited rather than racing the daemon.
	waitForExit(t, name)

	found, err := client.ListContainers(context.Background(), map[string]string{"steps.test.owner": "exited"})
	if err != nil {
		t.Fatalf("ListContainers: %v", err)
	}

	if len(found) != 1 {
		t.Errorf("found %d containers, want the exited one — those are the orphans worth reclaiming", len(found))
	}
}

// removeFixture takes a fixture container away on its own bounded context,
// since a cleanup runs after the test's own is already done.
func removeFixture(name string) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	//nolint:gosec // a name this test generated
	_ = exec.CommandContext(ctx, "docker", "rm", "-f", name).Run()
}

func waitForExit(t *testing.T, name string) {
	t.Helper()

	for range 50 {
		//nolint:gosec // a name this test controls
		out, err := exec.CommandContext(context.Background(), "docker", "inspect", "-f", "{{.State.Status}}", name).Output()
		if err == nil && strings.TrimSpace(string(out)) == "exited" {
			return
		}

		time.Sleep(100 * time.Millisecond)
	}

	t.Skip("the fixture container did not exit in time")
}

func TestRemoveContainerRemovesARunningOne(t *testing.T) {
	client := requireDaemon(t)

	name := startLabelled(t, map[string]string{"steps.test.owner": "remove"})

	err := client.RemoveContainer(context.Background(), name)
	if err != nil {
		t.Fatalf("RemoveContainer: %v", err)
	}

	//nolint:gosec // a name this test generated
	inspectErr := exec.CommandContext(t.Context(), "docker", "inspect", "--type", "container", name).Run()
	if inspectErr == nil {
		t.Error("the container is still there; a step that timed out would strand it")
	}
}

// TestRemoveContainerToleratesAnAbsentOne pins that removing something already
// gone is the outcome this wanted, not a failure.
//
// It happens constantly: a container that exited on its own, a daemon that
// restarted, a teardown racing the sweep. Reporting it would put an error in
// the log of a run that cleaned up perfectly well — and this used to be
// decided by matching the words "No such container" in the CLI's output,
// which is a sentence the daemon was free to reword at any time.
func TestRemoveContainerToleratesAnAbsentOne(t *testing.T) {
	client := requireDaemon(t)

	err := client.RemoveContainer(context.Background(), "steps-test-never-existed")
	if err != nil {
		t.Errorf("RemoveContainer: %v, want a container that is already gone to be a success", err)
	}
}
